.\"
.\" ukui-about manual page.
.\" (C) 2010 Vincent Untz (vuntz@gnome.org)
.\"
.TH UKUI-ABOUT 1 "UKUI"
.SH NAME
ukui-about \- Learn more about UKUI
.SH SYNOPSIS
.B ukui-about [\-\-version]
.SH DESCRIPTION
The \fIukui-about\fP program is a tool to learn more about UKUI and
who creates UKUI. It contains an introduction about the project, and
lists all contributors.
.PP
The list of contributors used by \fIukui-about\fP is the list of
UKUI Foundation members.
.SH OPTIONS
The following options are supported:
.TP
.I "--version"
Output the UKUI version instead of running a graphical interface.
.SH BUGS
If you find bugs in the \fIukui-about\fP program, please report
these on http://bugzilla.gnome.org.
