.\"
.\" ukui-color-select manual page.
.\" (C) 2015 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
.\"
.TH ukui-color-select 1 "UKUI"
.SH NAME
ukui-color-select \- Select a color from a palette or from screen
.SH SYNOPSIS
.B ukui-color-select [<gtk-options>]
.SH DESCRIPTION
The \fIukui-color-select\fP program is a tool to pick a color from a
color palette or from screen. It is not meant to be used on its own, but
as a UKUI Desktop helper application.
.SH OPTIONS
The \fBukui-color-select\fR tool supports all known GTK options, but has no options of its own.
.SH BUGS
If you find bugs in the \fIukui-color-select\fP program, please report
these on https://github.com/ukui-desktop/ukui-desktop/issues.
